services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - .:/var/www/
    depends_on:
      - php
    environment:
      TZ: ${APP_TIMEZONE}

  php:
    container_name: php
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        TZ: ${APP_TIMEZONE}
    volumes:
      - .:/var/www

  redis:
    image: redis:latest
    container_name: redis
    environment:
      TZ: ${APP_TIMEZONE}
    volumes:
      - redis_data:/var/lib/redis

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
